package conformance

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/fuaran-ui/fuaran-go/opstream"
	"github.com/fuaran-ui/fuaran-go/wire"
)

// The op-stream hash-chain conformance leg: recompute every record's hash from
// the shared chain golden and assert byte-equal to the committed value. The
// golden is generated by the reference F# HashChain.computeHash; a mismatch is
// a bug in this host's chain, never the corpus.

type chainRecord struct {
	OpFixture            string          `json:"opFixture"`
	Sequence             int             `json:"sequence"`
	Actor                json.RawMessage `json:"actor"`
	PromptID             *string         `json:"promptId"`
	Result               json.RawMessage `json:"result"`
	TimestampUnixSeconds int64           `json:"timestampUnixSeconds"`
	PreviousHash         string          `json:"previousHash"`
	Hash                 string          `json:"hash"`
}

type chainCorpus struct {
	Version             int           `json:"version"`
	GenesisPreviousHash string        `json:"genesisPreviousHash"`
	Records             []chainRecord `json:"records"`
}

func decodeActor(t *testing.T, raw json.RawMessage) opstream.Actor {
	t.Helper()
	var probe struct {
		Kind    string `json:"kind"`
		ID      string `json:"id"`
		Model   string `json:"model"`
		Version string `json:"version"`
	}
	if err := json.Unmarshal(raw, &probe); err != nil {
		t.Fatalf("actor: %v", err)
	}
	switch probe.Kind {
	case "human":
		return opstream.HumanActor{ID: probe.ID}
	case "agent":
		return opstream.AgentActor{Model: probe.Model, Version: probe.Version, ID: probe.ID}
	default:
		t.Fatalf("unknown actor kind %q", probe.Kind)
		return nil
	}
}

func decodeResult(t *testing.T, raw json.RawMessage) opstream.OpResult {
	t.Helper()
	var probe struct {
		Kind    string `json:"kind"`
		Code    string `json:"code"`
		Message string `json:"message"`
	}
	if err := json.Unmarshal(raw, &probe); err != nil {
		t.Fatalf("result: %v", err)
	}
	if probe.Kind == "failure" {
		return opstream.Failure{Code: probe.Code, Message: probe.Message}
	}
	return opstream.Success{}
}

func TestChainCorpusGolden(t *testing.T) {
	corpus := findCorpus()
	if corpus == "" {
		t.Skip("wire-format-fixtures corpus not found alongside the repo; skipping (standalone checkout)")
	}
	raw, err := os.ReadFile(filepath.Join(corpus, "chain", "chain-corpus.json"))
	if err != nil {
		t.Skipf("chain corpus not found: %v", err)
	}
	var cc chainCorpus
	if err := json.Unmarshal(raw, &cc); err != nil {
		t.Fatalf("parsing chain corpus: %v", err)
	}
	if len(cc.Records) == 0 {
		t.Fatal("chain corpus declares no records")
	}
	if cc.Version != opstream.ChainFormatVersion {
		t.Fatalf("chain corpus version %d != host ChainFormatVersion %d", cc.Version, opstream.ChainFormatVersion)
	}

	previousHash := opstream.GenesisPreviousHash
	for _, rec := range cc.Records {
		t.Run(rec.OpFixture, func(t *testing.T) {
			op, err := wire.DecodeOp(readFixture(t, corpus, rec.OpFixture))
			if err != nil {
				t.Fatalf("decode op fixture: %v", err)
			}
			if rec.PreviousHash != previousHash {
				t.Fatalf("golden previousHash chain broke at seq %d", rec.Sequence)
			}
			got, err := opstream.ComputeHash(rec.PreviousHash, op, rec.Sequence, rec.TimestampUnixSeconds,
				decodeActor(t, rec.Actor), rec.PromptID, decodeResult(t, rec.Result))
			if err != nil {
				t.Fatalf("ComputeHash: %v", err)
			}
			if got != rec.Hash {
				t.Errorf("seq %d hash =\n %s\nwant\n %s", rec.Sequence, got, rec.Hash)
			}
		})
		previousHash = rec.Hash
	}
}
